fix: add @types/node to packages devDependencies (@nadalaba) (#7789)
after `"types": ["node"]` was added to the base tsconfig on e7cd1a0,
running `pnpm ts-check --force` fails:
> @monkeytype/tsup-config:ts-check: error TS2688: Cannot find type
definition file for 'node'.
@monkeytype/tsup-config:ts-check:   The file is in the program because:
@monkeytype/tsup-config:ts-check: Entry point of type library 'node'
specified in compilerOptions

Co-authored-by: Jack <jack@monkeytype.com>