fix(test): disable solid HMR in tests to fix path error on Windows (@nadalaba) (#7677)
### Description

Solid’s refresh runtime is injecting a virtual module that resolves to
an invalid `file:///@` URL causing tests to fail on Windows:

> TypeError: The argument 'filename' must be a file URL object, file URL
string, or absolute path string. Received 'file:///@solid-refresh'

HMR isn’t used in vitest's SSR test environment, so disabling it on all
platforms is safe.